// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $api_test from "./routes/api-test.tsx";
import * as $docs from "./routes/docs.tsx";
import * as $index from "./routes/index.tsx";
import * as $monitoring from "./routes/monitoring.tsx";
import * as $Counter from "./islands/Counter.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/api-test.tsx": $api_test,
    "./routes/docs.tsx": $docs,
    "./routes/index.tsx": $index,
    "./routes/monitoring.tsx": $monitoring,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
